### ISSUE TITLE
Plugiin not executable, what abiout Debug.lua

### ISSUE THREAD

**Issue by axelstahlhut** [safx/LightroomPlugin-ClarifaiTagger#8]
I never can dexecute plugin. Thre is the file Debug.lua missing.

Error as follows:
![image](https://cloud.githubusercontent.com/assets/15837749/21417090/5e395fe0-c818-11e6-9b2c-724c3b389a76.png)

**Comment by LowellMontgomery** [comment]
Yes, thank you @axelstahlhut, for your feedback. The debugging toolkit was recently added while making some improvements. It should work (as-is) if you rename the plugin from .lrdevplugin to .lrplugin... but I have just removed the debugger and created a new commit to master so that nobody else has to be confused by this. I will not be doing much further development of this plugin. Related development will continue in another project (in collaboration with another Github dev): https://github.com/mcrosson/lr_plugin_computer_vision_tagging  In many ways, I think the approach of an "export plugin" is better, all around.

That said, this plugin should work for you now if you update to the latest state.

**Comment by axelstahlhut** [comment]
Hi Lowell, great, thanks a lot. I am a little helpless, am a pure Java / SAP Hybris Developer and Consultant and completely new to that Adobe scripting stuff. But I had the sane idea to build sth. On Google Vision API when I found your project Axel Stahlhut sth. To learn from. Maybe I can join the other project? I’d really like to!
Cheers Axel

**Comment by LowellMontgomery** [comment]
@axelstahlhut I feel your pain when it comes to the learning curve. It takes a while to get used to. First you should learn the basics of Lua, then you need to learn your way around the basics of the Lightroom SDK/API, which is not very nicely documented. None of it is very easy to find good examples of compared to popular coding languages like C++, Java, PHP, Javascript, etc. That is partly why I wanted to make my contributions here more public (to at least help the "next guys").

The other project already has the Google Vision API in the "roadmap" and your help implementing it would be welcome, I'm sure. 👍 

You'll learn by experience and there are online forums where others may provide support if you run into problems, but collaborating really helps a lot.

Cheers,

Lowell

**Comment by axelstahlhut** [comment]
Hey Lowell,


Already made some tests with the vision tutorials, did the iPhone 7 App (also new to that). Using the API with Java is the most convenient to me, don’t know how easily one could integrate Java into Lua Scripts?
Ok, I#ll hae a look at that project and ask then for being accepted Axel Stahlhut contributor/committer. That would be the right way, would it?
You see, I am not really involved into OpenSource projects until now, too.

Years ago I stared translating the documentation for Hin´berate to German, but that it was already ;-)

I do appreciate very much you guys making that Lua stuff here public, think it is definitely the best way to learn. Thank you!

Cheers,
Axel

**Comment by LowellMontgomery** [comment]
@axelstahlhut —  Hi Axel,

If your goal is to have a Lightroom plugin, then it's hard (I won't say impossible) to integrate other technologies (e.g. Java). There may be some tricks with regard to using Java via command-line calls from the Lua/Lightroom SDK, but that would require users all have Java installed. I know other Lightroom plugin developers _do_ make use of some non-Lua tools, though, so it's not impossible. So far, though, there are not a lot of examples for these kinds of novel "tricks". I know it is sometimes done, but then the code is most often compiled, so you won't see *how* it was achieved.

Normally, on Github, you make a fork (of an existing project), add features in a branch, test and make sure it's all working, then create a "pull request" to the project "owner" to merge the changes. In the case of this plugin, the originator (safx) gave me commit authorization to his project, so I have been able to merge my own pull requests lately, but that's just because he's a bit spread thin, I think, and doesn't normally work with Lua/Lightroom SDK. I think he mostly does Mac/iPhone/Swift development.

For the other "computer vision" plugin I've been collaborating on, @mcrosson is very involved and does a great job of managing his project. I'm sure you'll be able to find a way to be useful if your goal is to have a functional Lightroom plugin that leverages the Google Vision API. Most of the "heavy lifting" has already been achieved by Mike and myself, I think—inasmuch as there are many core functionalities that should not need to be reinvented (very much) for each service, so it should mostly be a matter of figuring out how to communicate with the Google system and how to interpret the responses.

Cheers,

Lowell

**Comment by mcrosson** [comment]
Indeed, the Lightroom Vision project I started does have the Google Computer Vision API and Amazon Vision API's as part of the long term roadmap [here (see the bottom section)](https://mcrosson.github.io/lr_plugin_computer_vision_tagging/project_plan/). I also started work on the Microsoft Vision API prior to @LowellMontgomery 's awesome work on the hierarchical tagging. The changes I started are [here](https://github.com/mcrosson/lr_plugin_computer_vision_tagging/commit/30b657340cf132aed5aff3e519cb2cbf6f095334). There is some refactoring that needs to be done in the linked commit but it should serve as a solid base for adding Google's Computer Vision API.

I'm hoping to make some more progress "soon" but real life has been pretty crazy for awhile and I'm working on getting some more free time to resume work on the Microsoft Vision API implementation.

**Comment by axelstahlhut** [comment]
Hi Lowell, 

I totally agree after seeing it is not a big thing if I learn lua.
With that GIT processes I am familiar after 15 years of Java development.
My goal is a bit special: I am an ambitioned photographer in my private times. 
I am doing mostly private projects and I am busy with building a shop for studio equipment. With 100% I am Java developer in a small company in Bremen and I am doing SAP hybris Projects with long runtimes.

Now i started a hybris training project for our newbies, and they decided (i pushed just a bit ;-) to build a Stock Photo Portal. For that we want to tag the photos, we will do it in Java, fine. But it is training. We will never set it productive.

But kow Axel Stahlhut I found Google Vision, I want it for myself. The second thing I would like to build is a "hub" from where i can select - in prefereneces eg., to which stock photo portal I want to upload. I work with LR, so I would like to build that as a plugin. Would be great if there would be a clean API, where eg. Me could integrate easily more target systems to upload. In my case I would most likely also have an interface to my NAS, and the typical candidates like Fotolia, Shutterstock, 500px,...

While writing I have also the idea to create interfaces to print companies like CEWE, Whitewall, Pixum and so on. Most probably this would be another plugin.

Kind regards,
Axel

**Comment by LowellMontgomery** [comment]
@axelstahlhut Most of these services/agencies have their own plugins for exporting to them; same with print companies. There are also other plugins and services that already do some integration and/or help you track where you have submitted what, etc. That said, if there is something to innovate in this area, I'd be happy to collaborate on that since establishing a stock photo portfolio was my original goal when I started working on these plugins to streamline some of the "metadata stuff".

Looking forward to collaborating... but first sleeping. ;-) (I'm only a few hours south of you—in Frankfurt.)

**Comment by axelstahlhut** [comment]
Hi Mike,

If you should need some help in case of MS development/Azure, I could surely activate a friend of mine. We are MS partners and especially very much busy with Azure stuff  - so just give me a hint.
If there is something to do for me, as Lua newbie but REST/Java/Cloud experienced developer, I would appreciate very much to join the project.

Kind regards,
Axel

**Comment by mcrosson** [comment]
@axelstahlhut  thank you for the offer to help. Right now I mostly need help with the LUA glue for the plugin. The Microsoft APIs are really really straight forward and I had no problems getting the fundamental API calls working. The trick now is getting the branch updated to work with @LowellMontgomery 's latest updates on the master along with polishing the implementation / testing.

I'd welcome any/all help you'd be willing to provide.

Also, if you continue forward with your stock photography work, please let me know. I'm curious what you are able to put together. Much like Lowell, I've been toying with some stock photography type stuff and the Computer Vision plugin was born to help with the metadata grunt work that has been involved.
